### ISSUE TITLE
hexo3.0 不支持

### ISSUE THREAD

**Issue by huixisheng** [coneycode/hexo-generator-baidu-sitemap#1]
rt

**Comment by PlatypusPro** [comment]
hexo generate时会报错...这是怎么回事...

**Comment by coneycode** [comment]
应该不是主题的问题。你换个主题应该也会挂。。hexo3.0的问题。建议先不要用3.0.改动很大，但是对用户而言价值不大。

**Comment by PlatypusPro** [comment]
我懒得再换回老版本了怎么办... = =
应该不是主题的事，装了就报错卸了就没事了
还会出hexo3.0的版本吗？我一直等着好了...反正现在又不着急...

**Comment by coneycode** [comment]
-_-!迷糊了。这几天有人主题报错。。你们原来是插件报错。。
会出的。。我现在就去改。。我写的两个插件都挂了。。-_-!

**Comment by PlatypusPro** [comment]
好的好的，谢谢啦~

**Comment by coneycode** [comment]
已经支持3.0的站图生成。请参照README.md

**Comment by PlatypusPro** [comment]
谢谢
