### ISSUE TITLE
问一个hexo插件开发的问题？ #6 @XuanmiaoG XuanmiaoG opened this issue  about 1 hour ago 如何制作一个hexo 插件，在每个页面中都追加一段js代码？ @XuanmiaoG XuanmiaoG  commented about 1 hour ago 希望给出代码

### ISSUE THREAD

**Issue by XuanmiaoG** [coneycode/hexo-generator-baidu-sitemap#13]
问一个hexo插件开发的问题？ #6
@XuanmiaoG
XuanmiaoG opened this issue 
about 1 hour ago
如何制作一个hexo 插件，在每个页面中都追加一段js代码？
@XuanmiaoG
XuanmiaoG 
commented about 1 hour ago
希望给出代码

**Comment by coneycode** [comment]
你这是问问题么。如何制作？希望给出代码？怎么感觉像我直接把插件写好给你的意思。。
