### ISSUE TITLE
标题里含有 ‘&’ 字符时有 error

### ISSUE THREAD

**Issue by Cloverii** [coneycode/hexo-generator-baidu-sitemap#15]
如题，我的 baidusitemap.xml 文件在浏览器里打开时显示如下错误
```
This page contains the following errors:

error on line 167 at column 35: xmlParseEntityRef: no name
Below is a rendering of the page up to the first error.
```
按照[这个链接](http://stackoverflow.com/questions/7604436/xmlparseentityref-no-name-warnings-while-loading-xml-into-a-php-file)里的方法把某篇文章标题里的 `&` 改成 `&amp;` 就好了，请问可不可以添加上这个字符编码的功能呢？

**Comment by coneycode** [comment]
收到，我看一看，多谢。

**Comment by aeolusheath** [comment]
@coneycode  标题有<>符号 会报错。。生成的xml报 <> 没有结束标签。。

**Comment by coneycode** [comment]
这个百度map的格式总是变，真是崩溃。。我还得去更新下。。

**Comment by upupming** [comment]
Duplicate of #25

**Comment by coneycode** [comment]
收到，更新后会通知大家

**Comment by coneycode** [comment]
done~
