### ISSUE TITLE
在public里生成的map文件，hexo d部署后，github上没有是什么情况

### ISSUE THREAD

**Issue by bigdots** [coneycode/hexo-generator-baidu-sitemap#16]

**Comment by coneycode** [comment]
hexo d部署后没有？.gitignore里没屏蔽吧？部署成功了，但是public里有，git里没有.xml文件是嘛？

**Comment by bigdots** [comment]
嗯嗯，是的。public里有，git里没有.xml文件

**Comment by bigdots** [comment]
.gitignore文件：没有屏蔽啊


.DS_Store
Thumbs.db
db.json
*.log
node_modules/
public/
.deploy*/

**Comment by coneycode** [comment]
我试一试。

**Comment by bigdots** [comment]
。。。。。。最后是我的全局里屏蔽了

**Comment by coneycode** [comment]
搞定就好。。。
