### ISSUE TITLE
hexo 3.3.7 版本无法生成 baidusitemap.xml

### ISSUE THREAD

**Issue by GFigure** [coneycode/hexo-generator-baidu-sitemap#17]
安装了` hexo-generator-sitemap@1.2.0` 和 `hexo-generator-baidu-sitemap@0.1.1 `

`hexo clean && hexo g` 后发现无法生成 `baidusitemap.xml`

调试时发现`rename  baidusitemap.xml -> sitemap.xml `，不知道是不是只有我个人出现这样的问题。

后来直接在主题配置文件里 只配置
```
baidusitemap: 
  path: baidusitemap.xml
```

才可以生成` baidusitemap.xml`，而且也生成了 `sitemap.xml`，不知道为什么？？？

**Comment by coneycode** [comment]
多谢，我看一看。

**Comment by dwj999** [comment]
我的hexo 3.3.7版本，执行以下都不行，都不会生成baidusitemap.xml
npm install hexo-generator-baidu-sitemap --save
npm install hexo-generator-baidu-sitemap@0.1.1 --save
npm install hexo-generator-baidu-sitemap --save-dev
npm install hexo-generator-baidu-sitemap@0.1.1 --save-dev

站点目录配置如下：
sitemap: 
    path: sitemap.xml
baidumap: 
path: baidusitemap.xml

**Comment by ArchitectBeaver** [comment]
Hexo版本:  `hexo 3.3.8` and `hexo-cli 1.0.3.` 
同时安装了 `hexo-generator-sitemap@1.2.0` 和 `hexo-generator-baidu-sitemap@0.1.1` 
产生和@GFigure 同样的问题

**Comment by coneycode** [comment]
收到。

**Comment by coderunner-xinxin** [comment]
请问issue解决了吗😊

**Comment by coneycode** [comment]
done，请更新到最新版本~
