### ISSUE TITLE
npm ERR! invalid: hexo-generator-baidu-sitemap@0.0.8

### ISSUE THREAD

**Issue by shijiebei2009** [coneycode/hexo-generator-baidu-sitemap#19]
```
hexo: 3.3.5
hexo-cli: 1.0.3
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 7.10.1
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j

WX@WX-PC /d/hexo (master)
$ npm -v
4.2.0
```

```
$ npm list --depth=0
hexo-site@0.0.0 d:\hexo
+-- exec-buffer@0.1.1
+-- hexo@3.3.5
+-- hexo-console-optimize@0.0.5
+-- hexo-deployer-git@0.3.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-baidu-sitemap@0.1.2
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.0
+-- hexo-util@0.6.1
--- hexo-wordcount@3.0.2

npm ERR! invalid: hexo-generator-baidu-sitemap@0.0.8 d:\hexo\node_modules\hexo-g
enerator-baidu-sitemap\node_modules\hexo-generator-baidu-sitemap
```
这个原因是为啥呢？remove 0.0.8之后还是这样

**Comment by coneycode** [comment]
我试试

**Comment by shijiebei2009** [comment]
$ npm list --depth=0
hexo-site@0.0.0 d:\hexo
+-- es5-ext@0.10.35
+-- exec-buffer@0.1.1
+-- hexo@3.3.5
+-- hexo-deployer-git@0.3.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-baidu-sitemap@0.1.2
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.0
+-- hexo-symbols-count-time@0.2.0
`-- hexo-util@0.6.1

npm ERR! invalid: hexo-generator-baidu-sitemap@0.0.8 d:\hexo\node_modules\hexo-g
enerator-baidu-sitemap\node_modules\hexo-generator-baidu-sitemap

@coneycode

**Comment by coneycode** [comment]
done~请更新到最新版本
