### ISSUE TITLE
为什么显示抓取失败呢？

### ISSUE THREAD

**Issue by PlatypusPro** [coneycode/hexo-generator-baidu-sitemap#2]
![](http://i2.tietuku.com/1b7f79c9b67bb2c1.png)

**Comment by coneycode** [comment]
显示连接超时。。也就是根本没有链接到你提供的地址。
你的blog托管在哪？

**Comment by PlatypusPro** [comment]
[http://platypuspro.github.io/baidusitemap.xml](http://platypuspro.github.io/baidusitemap.xml)
baidusitemap.xml就放在我的blog的根目录

**Comment by coneycode** [comment]
这个是超时问题。如果你确认这个页面成功生成了，应该不是我插件的原因。你过一会再试试呢？

**Comment by PlatypusPro** [comment]
![](http://i3.tietuku.com/32fc42f10ac371e0.png)
还是失败...

**Comment by coneycode** [comment]
我刚去看了看，我用在2.8的hexo上。以前都没问题。现在也报403了。403是访问不到的意思。应该是百度抓不到github的这个页面了。这个是百度的问题。。跟我插件关系不大。

**Comment by PlatypusPro** [comment]
哦...那好吧...谢谢你啦

**Comment by coneycode** [comment]
也有可能是github被墙了。我晚上换到gitcafe上试试。

**Comment by PlatypusPro** [comment]
唉...傻逼的GFW...

**Comment by tvvocold** [comment]
@coneycode 
可以提交 bug 到 https://github.com/BaiduQA

**Comment by xiaoxuetu** [comment]
github被百度给墙了

**Comment by tvvocold** [comment]
可以来试试 Coding 的免费演示空间 
http://blog.csdn.net/itmyhome1990/article/details/43759411

**Comment by GeneralLi95** [comment]
出现了和你同样的问题，不知道你解决了没有
