### ISSUE TITLE
安装完后，hexo d -g报错

### ISSUE THREAD

**Issue by Arthurwu24** [coneycode/hexo-generator-baidu-sitemap#20]
`npm install hexo-generator-baidu-sitemap --save-dev`成功。

然后，`hexo d -g`报错。

![image](https://user-images.githubusercontent.com/9261202/34215158-80ef14ae-e5df-11e7-8e70-348cd7ffc23a.png)

谷歌搜索到有一位也是类似报错信息的 `post.tags.toArray is not a function`。

[hexo报错之生成报错](http://igoodgoodstudy.com/2017/08/14/hexo%E6%8A%A5%E9%94%99%E4%B9%8B%E7%94%9F%E6%88%90%E6%8A%A5%E9%94%99/)

但好像显示的又不太一样，他的解决措施我也没遇到类似的问题，无法通过他的解决方式解决...

**Comment by coneycode** [comment]
难道hexo又改版了。。沃德天。。。

**Comment by Arthurwu24** [comment]
![image](https://user-images.githubusercontent.com/9261202/34289292-cb499f8a-e72c-11e7-95e9-d3fc464aeb72.png)

这是我的hexo的版本信息...

**Comment by coneycode** [comment]
收到了。。我有时间看一看。。多谢反馈

**Comment by lewky** [comment]
我也遇到这个问题了，我的Hexo版本是3.7.1
我的解决方式是将node_modules\hexo-generator-baidu-sitemap\baidusitemap.ejs里边的post.tags.toArray()和post.categories.toArray()改成post.tags和post.categories，简单的说就是把这里的toArray()去掉，新版本的Hexo的tags和categories可以直接遍历

**Comment by coneycode** [comment]
done~
