### ISSUE TITLE
hexo 3.x can not generate baidusitemap.xml

### ISSUE THREAD

**Issue by liadbiz** [coneycode/hexo-generator-baidu-sitemap#23]
Hi, I am using hexo 3.6.0. According to your doc, I should config like this:

```bash
baidusitemap:
path: baidusitemap.xml
```
but after that, I ran `hexo g`. Then, I checked out the `public` directory and found that there are no file `baidusitemap.xml`.

Did I use it in a wrong way?

**Comment by lewky** [comment]
@liadbiz 
Because Hexo 3.X.X has upgraded some code.
You can alter the file : `node_modules\hexo-generator-baidu-sitemap\baidusitemap.ejs`, change `post.tags.toArray()` to `post.tags` and change `post.categories.toArray()` to `post.categories`. Then you can generate baidusitemap.xml successfully.

**Comment by liadbiz** [comment]
@lewky  Thanks! I will try it later.

**Comment by coneycode** [comment]
Later will update it

**Comment by coneycode** [comment]
done~
