### ISSUE TITLE
标题里面含有一些特殊符号，sitemap会出现解析不正确

### ISSUE THREAD

**Issue by LittleWhite-Carry** [coneycode/hexo-generator-baidu-sitemap#25]
我的是标题里面有&，在转成xml的时候应该变成实体命名。参考如下链接
https://blog.csdn.net/goon_star/article/details/49636505
希望能增加一下，把标题或者标签等里面有的特殊符号变成实体命名

**Comment by upupming** [comment]
我也遇到这个问题了。
![screenshot from 2018-06-28 12-05-28](https://user-images.githubusercontent.com/24741764/42012590-9657684c-7acb-11e8-8d88-92560d1b974d.png)
查了查 [stackoverflow](https://stackoverflow.com/questions/7823813/how-can-i-use-character-in-xml-code)，修改 `node_modules/hexo-generator-baidu-sitemap/baidusitemap.ejs`加上 `![CDATA[]]` 就好了。
```
<title>![CDATA[Abstraction Functions & Rep Invariants]]</title>
```
<hr>

不过作者好像已经在[这个 commit](https://github.com/coneycode/hexo-generator-baidu-sitemap/commit/52e462ee341814714592f0f1fdfa4bbdfebd8a97)里面删除了 `title` 字段（`title` 字段对搜索引擎确实没有什么用处），但是却没有更新 npm 仓库，所以大家现在使用的还是之前有 `title` 字段的旧版。
我主动更新了一下，你可以使用我发布的。
``` bash
$ npm remove hexo-generator-baidu-sitemap
$ npm install hexo-generator-baidu-sitemap-new@0.1.2 --save
```

**Comment by coneycode** [comment]
收到，更新后会通知大家~

**Comment by coneycode** [comment]
已处理~
