### ISSUE TITLE
为什么要依赖自身0.0.8版本的包

### ISSUE THREAD

**Issue by betterliyu** [coneycode/hexo-generator-baidu-sitemap#26]
"dependencies": {
    "ejs": "^1.0.0",
    "hexo": "^3.0.0",
    "hexo-generator-baidu-sitemap": "0.0.8",
    "utils-merge": "^1.0.0"
  },

为什么要依赖hexo-generator-baidu-sitemap@0.0.8. 这行代码是不是可以删除。否则会出现错误invalid: have hexo-generator-baidu-sitemap@0.0.8

**Comment by coneycode** [comment]
额，我想想当时为什么这么做。时间有点长了，如果没用的话我就干掉它。但是应该不影响编译吧？

**Comment by betterliyu** [comment]
不影响编译，但是执行npm shrink就会报错。

**Comment by coneycode** [comment]
已处理~
