### ISSUE TITLE
What's the difference between 2.xx and 3.xx?

### ISSUE THREAD

**Issue by Aqua-Dream** [coneycode/hexo-generator-baidu-sitemap#29]
In readme, you say

if your hexo version is 2.x.x, you can configure this plugin in _config.yml.
```
baidusitemap:
    path: baidusitemap.xml
```
if version is 3.x.x, you should configure this plugin in _config.yml.
```
baidusitemap:
path: baidusitemap.xml
```
So the only difference is that in 3.x.x we don't need the white spaces before 'path'?

**Comment by coneycode** [comment]
emm，
I don't know the reason, in fact,
if you use the white spaces in 3.x.x,  
then something wrong.

**Comment by Aqua-Dream** [comment]
OK... Just I've never seen config writing in this way before...
