### ISSUE TITLE
具体使用流程

### ISSUE THREAD

**Issue by ming15** [coneycode/hexo-generator-baidu-sitemap#6]
当我把这个插件安装完之后，只需要在_config.yml添加
```
baidusitemap:
    path: baidusitemap.xml
```
就可以了是啊？还需要添加其他的文件或者执行其他的命令吗

**Comment by coneycode** [comment]
baidusitemap:
path: baidusitemap.xml 
hexo3.0的话，
baidusitemap:
    path: baidusitemap.xml
不好使了。我忘记改Readme了，抱歉。
