### ISSUE TITLE
baidusitemap.xml does not generate

### ISSUE THREAD

**Issue by winterTTr** [coneycode/hexo-generator-baidu-sitemap#7]
You can use my repository to reproduce this issue.
https://github.com/winterTTr/winterTTr.github.io/tree/hexo-content

Use the `hero-content` branch of my repository and `hero g`, `baidusitemap.xml`does not generate.
No error shows, and I have test with reinstall this plugin and whole hero environment.
Could you give any suggestion?

**Comment by coneycode** [comment]
if you use hexo3.0,
config will be better as it:
baidusitemap:
path: baidusitemap.xml

**Comment by winterTTr** [comment]
https://github.com/winterTTr/winterTTr.github.io/blob/hexo-content/_config.yml

Here is my config, you can find it already has the `baidusitemap` section in it.

**Comment by coneycode** [comment]
# baidu sitemap
baidusitemap:
  path: baidusitemap.xml

should relplaced by it:
# baidu sitemap
baidusitemap:
path: baidusitemap.xml

**Comment by winterTTr** [comment]
Sorry, i cannot find any difference from your previous comments.
Maybe you miss to change something? The two parts seems totally the same.

**Comment by winterTTr** [comment]
Finally, I think I found the issue.
Here is the pull request #8 to fix it.
Please review and merge if you agree.

**Comment by coneycode** [comment]
Thanks for you commit.
