### ISSUE TITLE
百度站内搜索校验失败

### ISSUE THREAD

**Issue by dxjia** [coneycode/hexo-generator-baidu-sitemap#9]
Hi,
生成的baidusitemap文件在手动提交到百度站内搜索后，出现解析错误，如下：
![error-1](http://7xqitw.com1.z0.glb.clouddn.com/baidu-site-search-sitemap-error-1.png)
是我使用不对吗？
![error-1](http://7xqitw.com1.z0.glb.clouddn.com/baidu-site-search-sitemap-error-2.png)

**Comment by coneycode** [comment]
。。难道百度又改格式了。。这么恶心，稍后我去看看。。

**Comment by muxiaobai** [comment]
改格式了，loc参数变了，没有title了，%>_<%
[XML新规范](http://zhanzhang.baidu.com/site/format?id=1979)，

**Comment by coneycode** [comment]
崩溃了，我去看看

**Comment by muxiaobai** [comment]
不支持https？额(⊙o⊙)…

**Comment by coneycode** [comment]
不支持https,这个是百度的问题吧。

**Comment by muxiaobai** [comment]
嗯，（死百度），没有title了，

**Comment by zongren** [comment]
现在能用了吗

**Comment by vivatakethat** [comment]
现在能用吗？我自己尝试了几次  百度还是提示  无效的xml文件

**Comment by coneycode** [comment]
你是挂在了github上吧？github上百度抓不到。

**Comment by JinQzzz** [comment]
我的没挂git, 放在国外主机上, 也是无法抓取... https://ayano.moe/baidusitemap.xml

**Comment by coneycode** [comment]
好的，我去看看。

**Comment by gunsluo** [comment]
![image](https://cloud.githubusercontent.com/assets/9067076/21962586/e60ca6e4-db63-11e6-9b37-8d18a355af67.png)

我有同样的问题。 怎么解决的？

**Comment by coneycode** [comment]
百度的格式又换了。。真是崩溃。。等我改完格式更新。。

**Comment by coneycode** [comment]
请各位提供具体报错原因~以供排查~

**Comment by dengyuhan** [comment]
是格式问题，插件生成的是这样的

<img src="https://user-images.githubusercontent.com/17588779/62603830-5907ec80-b929-11e9-9474-a8b543184fd0.png" width="200"/>

我把它格式化后百度就能正常解析了

<img src="https://user-images.githubusercontent.com/17588779/62603903-75a42480-b929-11e9-8628-ca2184536a52.png" width="150"/>

**Comment by coneycode** [comment]
多谢，我去看看这个问题。

**Comment by KumaNNN** [comment]
问题多多呢，看来暂时不想用此插件了，话说，原作者的仓库呢，没了么，Readme里标注的是这个仓库本身的地址啊。 @coneycode

**Comment by coneycode** [comment]
我就是原作者。。不过最近不用hexo了，维护频率比较低。

**Comment by coneycode** [comment]
问题已解决，请更新版本。
